---
title: "DGP3 Size check"
author: "Taewook Lee and Changryong Baek"
date: "7/15/2019"
output: html_document
---

```{r, message=FALSE}  
rm(list = ls(all=TRUE))
setwd("/Users/crbaek/Dropbox/Public/BWildBoot/program")
source("cusum-blockWB-library2.R")
library(fGarch)

longrun_bartlett

cusum.bartlett.WB = function(data,boots,n.block) {
  
  t <- length(data)
  n.bl = n.block
  
  CUSUM.WB = c()
  reject.WB <- c()
  
  ## CUSUM test 
  
  CUSUM <- cusum.bartlett(data)$tn
  
  ## Wild bootstrap CUSUM test and its p-value
  
  w <- c(-1,1)  ## Rademacher distribution
  CUSUM.WB <- c()
  
  for(i in 1:boots){
    wt <- rep(sample(w,(t/n.bl+1),replace=TRUE),each=n.bl)[1:t]
    data.WB <- data*wt
    CUSUM.WB[i] <- cusum.bartlett(data.WB)$tn
  }
  
  try.reject <- try(ifelse(quantile(CUSUM.WB, prob=c(0.95))<CUSUM,1,0),TRUE)
  
  out = list();
  out$reject  =  try.reject
  return(out)
  
}

cusum.comparison.mean = function(r,t,b,m1,m2,ar.c){
  
  cusum.b = cusum.b.WB1 = cusum.b.WB2 = cusum.b.WB3 = numeric(r);

  library(doParallel)
  n.cl=detectCores(logical=TRUE)-1;
  cl <- makeCluster(n.cl)  
  registerDoParallel(cl) 
  Tstat.WB = foreach(b=1:r, .combine=rbind, .export=c("cusum.bartlett", "cusum.bartlett.WB", "sup_abs_bbridge", "longrun_bartlett") ) %dopar% {
    n_data = t/2;
    
    ## AR(1)
    rt = arima.sim(n = t, rand.gen = rnorm, list(order=c(1,0,0), ar=ar.c), sd=sqrt(1-ar.c^2))  
    rt1 = m1 + rt[1:n_data]
    rt2 = m2 + rt[(n_data+1):t]      
    rt = c(rt1,rt2)  

    n.b2 = floor(1.5*log(t));
    n.b3 = floor(1.5*sqrt(t));
    fit = cusum.bartlett(rt);
    
    rhohat =  ar.ols(rt, FALSE, order=1);
    rhohat = rhohat$ar[1];
    q = 1.1447*(t*4*rhohat^2/(1-rhohat^2)^2)^(1/3);
    n.b1 = floor(q);

    c(fit$pval, cusum.bartlett.WB(rt,199,n.b1), cusum.bartlett.WB(rt,199,n.b2), cusum.bartlett.WB(rt,199,n.b3))
    }
  
  stopCluster(cl)
    
    
  out = list();
  out$cusum.b  =  length(which(Tstat.WB[,1] < 0.05))/r
  out$cusum.b.WBlog  =   length(which(Tstat.WB[,3]==1))/r
  out$cusum.b.WBsqrt  =   length(which(Tstat.WB[,4]==1))/r
  out$cusum.b.WB1  =   length(which(Tstat.WB[,2]==1))/r
  
  out1 = unlist(out)
  return(out1)  
  
}
```

## Check for $\rho = .9$

```{r}
m1=0.0; m2=0; 
## AR(1) model

Tt = c(500, 1000, 2000, 5000)
out1 = NULL;
for(i in 1:4){
  print('===========')
  out1 = rbind(out1, cusum.comparison.mean(r=1000,Tt[i],b=199,m1,m2,ar.c=.90));
}
print(out1)
```



